spring:
  spring:
    data:
      mongodb:
        username: mongo_user
        password: mongo_password
        host: localhost
        port: 27017
        database: customer
        authentication-database: admin

  application:
    name: customer-service
  
server:
  port: 8090
