
services:
  postgres:
    container_name: ms_postgres_sql
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_db
      - PGDATA=/var/lib/postgresql/data

    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: ms_mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
      - MONGO_INITDB_DATABASE=mongo_db
    volumes:
      - mongodb:/data
    ports:
      - "27017:27017"
    networks:
      - microservices-net
    restart: unless-stopped

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongo_password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    restart: unless-stopped

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev:latest
    ports:
      - "1080:80" # Web UI
      - "1025:25" # SMTP Server

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongodb: